android.enableJetifier=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1536m
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.compose=false
android.defaults.buildfeatures.dataBinding=false
android.defaults.buildfeatures.prefab=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.defaults.buildfeatures.viewBinding=false
org.gradle.java.home=/Users/mgalhardo/.gradle/jdks/eclipse_adoptium-17-aarch64-os_x.2/jdk-17.0.20+8/Contents/Home
kotlin.daemon.jvmargs=-Djava.version=17.0.2
org.gradle.caching=true
org.gradle.configuration-cache=true
