android.enableJetifier=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1536m
android.defaults.buildfeatures.compose=false
android.defaults.buildfeatures.dataBinding=false
android.defaults.buildfeatures.prefab=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.defaults.buildfeatures.viewBinding=false
org.gradle.caching=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
