apply plugin: 'com.android.library'
apply plugin: 'kotlin-multiplatform'

ext {
    PUBLISH_ARTIFACT_ID = 'retained-core'
}

apply from: "${rootProject.projectDir}/scripts/publish-module.gradle"

android {
    namespace 'dev.marcellogalhardo.retained.core'
    compileSdk 37

    publishing {
        singleVariant('release')
    }

    defaultConfig {
        minSdk 23
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests {
            returnDefaultValues = true
        }
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
            allWarningsAsErrors = true
            freeCompilerArgs.add("-Xexplicit-api=strict")
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation libs.kotlin.stdlib
                implementation libs.androidx.lifecycle.runtime
                implementation libs.androidx.viewmodel.core
                implementation libs.androidx.viewmodel.savedstate
                implementation libs.androidx.savedstate
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test')
                implementation libs.junit.core
                implementation libs.google.truth
                implementation libs.androidx.viewmodel.testing
            }
        }
    }
}
