apply plugin: 'com.android.library'
apply plugin: 'kotlin-multiplatform'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

ext {
    PUBLISH_ARTIFACT_ID = 'retained-compose'
}

apply from: "${rootProject.projectDir}/scripts/publish-module.gradle"

android {
    namespace 'dev.marcellogalhardo.retained.compose'
    compileSdk 35

    publishing {
        singleVariant('release')
    }

    defaultConfig {
        minSdk 23
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        compose true
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
            allWarningsAsErrors = true
            freeCompilerArgs.add("-Xexplicit-api=strict")
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                api projects.core

                implementation libs.kotlin.stdlib
                implementation libs.androidx.viewmodel.core
                implementation libs.androidx.viewmodel.compose
            }
        }
        androidMain {
            dependencies {
                implementation libs.androidx.activity.core
                implementation libs.androidx.compose.ui
            }
        }
        commonTest {
            dependencies {
                implementation libs.junit.core
            }
        }
    }
}
