apply plugin: 'com.vanniktech.maven.publish'

mavenPublishing {
    coordinates('dev.marcellogalhardo', PUBLISH_ARTIFACT_ID, '2.0.0-alpha01')

    pom {
        name = PUBLISH_ARTIFACT_ID
        description = 'Retained is a lightweight Kotlin Multiplatform library built on top of AndroidX ViewModel. It provides a unified API to retain object instances across Kotlin Multiplatform targets.'
        url = 'https://github.com/marcellogalhardo/retained'
        licenses {
            license {
                name = 'The Apache Software License, Version 2.0'
                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
            }
        }
        developers {
            developer {
                id = 'marcellogalhardo'
                name = 'Marcello Galhardo'
                email = 'marcello.galhardo@gmail.com'
            }
        }
        scm {
            connection = 'scm:git:github.com/marcellogalhardo/retained.git'
            developerConnection = 'scm:git:ssh://github.com/marcellogalhardo/retained.git'
            url = 'https://github.com/marcellogalhardo/retained/tree/main'
        }
    }

    publishToMavenCentral("CENTRAL_PORTAL")

    if (rootProject.ext["signing.keyId"]?.trim()) {
        signAllPublications()
    }
}
